

name: CI


on:
  push:
    branches: [ "main" ]

  
  workflow_dispatch:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependecies
        run: npm install
      - name: check code style
        run: npx prettier ./src/ --check
  build:
    
    runs-on: ubuntu-latest
    needs: [ lint ]
    
   
    steps:
      
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: docker build -t ghcr.io/n0s0k69/22.11.24/node:latest ./app/
     
      - name: send telegram message on push  
        uses: appleboy/telegram-action@master
        with:
            to: 979715547
            token: 7243039707:AAHh4Y_9AFL7OOnN2nkz3xYRUxQsXYzwVL8
              
            message: |
                success

     
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
